-- 0097 · La tiquetera reserva sin pagar, jugando en el cupo de suelta.
--
-- Damián, 24 de septiembre: quiere vender paquetes de clases prepago
-- (4 por $52.000, 8 por $96.000 — ya en las piezas de campaña). Cuando
-- alguien con tiquetera entra a la página, tiene que poder reservar SIN
-- que se le cobre otra vez: pone una clave, la página la valida, y esa
-- clase se descuenta de su paquete.
--
-- LA DECISIÓN DE ARQUITECTURA
--
-- Al cambio de horario (0095) le dimos un cupo APARTE, chiquito, que no
-- toca cupo_tomado — porque ahí se estaba apostando al margen de
-- inasistencia de mensualidad, no vendiendo un cupo de verdad.
--
-- La tiquetera es distinta: es una clase suelta pagada por adelantado.
-- Ocupa exactamente la misma silla que le vendería a alguien que paga en
-- el momento. Por eso NO tiene cupo propio — juega en el mismo
-- `cupo_sueltas` / `cupo_tomado` que la suelta de siempre. Confirmado con
-- Damián: "se descuenta de las clases sueltas que están en venta para
-- ese día".
--
-- Dos decisiones de negocio, confirmadas antes de tocar el esquema:
--   · Quién puede vender una tiquetera: cajero, administrador y
--     propietario — los tres roles de admin_tokens existentes, así que
--     alcanza con pedir cualquier token válido.
--   · No-show con tiquetera: se descuenta igual, sin gracia. Por eso
--     `admin_marcar_no_vino` (que le da 3 días de crédito a una suelta
--     que no llegó) se cierra en seco para tipo 'tiquetera' — el cupo ya
--     se gastó al reservar, no hay nada que anotarle.
--
-- LO QUE SE CREA
--   · tipo_reserva gana el valor 'tiquetera' (transacción propia:
--     Postgres no deja usar un valor de enum nuevo en la misma
--     transacción que lo crea).
--   · tabla `tiqueteras`: código (la clave que la clienta escribe),
--     nombre, teléfono, cuántas clases trae, cuántas ha usado, cuándo
--     vence, si sigue activa.
--   · reservas gana `tiquetera_id`, para saber de cuál tiquetera salió
--     cada clase.
--   · admin_tiquetera_crear: la vende y genera el código.
--   · admin_tiqueteras_listar: para verla en el panel con su saldo.
--   · tomar_cupo aprende p_tipo = 'tiquetera' + p_codigo_tiquetera: NO
--     cobra, comparte el techo de suelta, y descuenta el saldo cuando la
--     reserva ya quedó insertada (nunca antes: si algo de arriba fallara,
--     no queremos una tiquetera gastada sin una reserva real detrás).
--   · admin_marcar_no_vino distingue tiquetera de miembro en el mensaje,
--     con el mismo resultado de siempre: no se le regala nada.
--
-- Se parchea EN SITIO sobre pg_get_functiondef, con anclajes verificados
-- por posición contra la definición viva antes de escribir esto: producción
-- trae ajustes que no están en este repo.

-- ── 1. el tipo nuevo, en su propia transacción ──────────────────────
-- alter type tipo_reserva add value if not exists 'tiquetera';
-- (aplicado en una llamada aparte -- ver el LEEME de despliegue de este
-- repo; Postgres no deja usar un valor de enum nuevo en la misma
-- transacción en la que se crea, así que esta línea ya corrió sola.)

-- ── 2. la tabla ──────────────────────────────────────────────────────
create table if not exists tiqueteras (
  id             bigint generated by default as identity primary key,
  -- La clave que la clienta escribe en la página. Mismo alfabeto que
  -- generar_codigo_reserva(): sin O/0/I/1, para que no haya dudas al
  -- dictarlo por teléfono.
  codigo         text not null,
  nombre         text not null,
  telefono       text not null,
  clases_totales int  not null,
  clases_usadas  int  not null default 0,
  precio_cop     int,
  creada_en      timestamptz not null default now(),
  creada_por     uuid references admin_tokens(id),
  vence_el       date not null,
  activa         boolean not null default true,
  constraint tiqueteras_clases_ck check (clases_totales > 0
    and clases_usadas >= 0 and clases_usadas <= clases_totales)
);

create unique index if not exists tiqueteras_codigo on tiqueteras (codigo);
create index if not exists tiqueteras_telefono on tiqueteras (telefono);

alter table tiqueteras enable row level security;
revoke all on table tiqueteras from public, anon, authenticated;

-- De cuál tiquetera salió cada clase reservada. Null para todo lo que
-- no sea tipo 'tiquetera'.
alter table reservas add column if not exists tiquetera_id bigint
  references tiqueteras(id);

-- ── 3. venderla ──────────────────────────────────────────────────────
--
-- Cualquier token de admin vivo alcanza: los tres roles que existen
-- (cajero, administrador, propietario) pueden vender una tiquetera en
-- el mostrador, igual que registran cualquier otro ingreso de caja.
create or replace function public.admin_tiquetera_crear(
  p_token text, p_nombre text, p_telefono text,
  p_clases int, p_vigencia_dias int, p_precio_cop int default null
) returns jsonb
language plpgsql security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
declare
  v_admin    uuid;
  v_nombre   text := trim(coalesce(p_nombre, ''));
  v_tel      text := solo_digitos(coalesce(p_telefono, ''));
  v_codigo   text;
  v_intentos int := 0;
  v_id       bigint;
  v_vence    date;
begin
  v_admin := verificar_token_admin(p_token);
  if v_admin is null then
    return jsonb_build_object('ok', false, 'error', 'NO_AUTORIZADO');
  end if;

  if length(v_nombre) < 2 then
    return jsonb_build_object('ok', false, 'error', 'NOMBRE_INVALIDO',
      'mensaje', 'Falta el nombre de quien compra la tiquetera.');
  end if;
  if length(v_tel) <> 10 then
    return jsonb_build_object('ok', false, 'error', 'CELULAR_INVALIDO',
      'mensaje', 'El celular debe tener 10 dígitos.');
  end if;
  if p_clases is null or p_clases < 1 or p_clases > 20 then
    return jsonb_build_object('ok', false, 'error', 'CLASES_INVALIDAS',
      'mensaje', 'El número de clases debe estar entre 1 y 20.');
  end if;
  if p_vigencia_dias is null or p_vigencia_dias < 1 or p_vigencia_dias > 365 then
    return jsonb_build_object('ok', false, 'error', 'VIGENCIA_INVALIDA',
      'mensaje', 'La vigencia debe estar entre 1 y 365 días.');
  end if;

  v_vence := (now() at time zone 'America/Bogota')::date + p_vigencia_dias;

  loop
    v_intentos := v_intentos + 1;
    v_codigo := generar_codigo_reserva();
    begin
      insert into tiqueteras (codigo, nombre, telefono, clases_totales,
                              precio_cop, vence_el, creada_por)
      values (v_codigo, v_nombre, v_tel, p_clases, p_precio_cop, v_vence, v_admin)
      returning id into v_id;
      exit;
    exception when unique_violation then
      if v_intentos >= 5 then raise; end if;
    end;
  end loop;

  return jsonb_build_object('ok', true, 'id', v_id, 'codigo', v_codigo,
    'nombre', v_nombre, 'clases', p_clases, 'vence_el', v_vence);
end;
$function$;

revoke all on function public.admin_tiquetera_crear(text, text, text, int, int, int)
  from public, anon, authenticated;
grant execute on function public.admin_tiquetera_crear(text, text, text, int, int, int)
  to service_role;

-- ── 4. verla en el panel ─────────────────────────────────────────────
create or replace function public.admin_tiqueteras_listar(
  p_token text, p_estado text default 'activas'
) returns jsonb
language plpgsql security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
declare
  v_admin uuid;
  v_hoy   date := (now() at time zone 'America/Bogota')::date;
  v_lista jsonb;
begin
  v_admin := verificar_token_admin(p_token);
  if v_admin is null then
    return jsonb_build_object('ok', false, 'error', 'NO_AUTORIZADO');
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
           'id', t.id, 'codigo', t.codigo, 'nombre', t.nombre,
           'telefono', t.telefono, 'clases_totales', t.clases_totales,
           'clases_usadas', t.clases_usadas,
           'clases_restantes', t.clases_totales - t.clases_usadas,
           'precio_cop', t.precio_cop, 'vence_el', t.vence_el,
           'activa', t.activa, 'creada_en', t.creada_en
         ) order by t.creada_en desc), '[]'::jsonb)
    into v_lista
    from tiqueteras t
   where case p_estado
           when 'activas' then t.activa and t.vence_el >= v_hoy
                                and t.clases_usadas < t.clases_totales
           else true
         end;

  return jsonb_build_object('ok', true, 'tiqueteras', v_lista);
end;
$function$;

revoke all on function public.admin_tiqueteras_listar(text, text)
  from public, anon, authenticated;
grant execute on function public.admin_tiqueteras_listar(text, text)
  to service_role;

-- ── 5. tomar_cupo aprende el camino tiquetera ────────────────────────
do $mig$
declare
  v_src text;
  v_a1 constant text := E'  v_cambios_tomados int;\n  v_tope_cambios    int;\nbegin';
  v_n1 constant text := E'  v_cambios_tomados int;\n  v_tope_cambios    int;\n  -- 0097: la tiquetera reserva sin cobrar, jugando en el mismo cupo\n  -- que la clase suelta.\n  v_tiquetera tiqueteras%rowtype;\nbegin';
  v_a2 constant text := 'CREATE OR REPLACE FUNCTION public.tomar_cupo(p_clase_id uuid, p_nombre text, p_telefono text, p_email text, p_origen text, p_tipo text DEFAULT ''suelta''::text)';
  v_n2 constant text := 'CREATE OR REPLACE FUNCTION public.tomar_cupo(p_clase_id uuid, p_nombre text, p_telefono text, p_email text, p_origen text, p_tipo text DEFAULT ''suelta''::text, p_codigo_tiquetera text DEFAULT NULL::text)';
  v_a3 constant text := E'    v_estado := ''confirmada'';\n  end if;\n\n  ------------------------------------------------------------------\n  -- Cupo compartido: el techo de la sala, siempre manda';
  v_n3 constant text := E'    v_estado := ''confirmada'';\n  end if;\n\n  ------------------------------------------------------------------\n  -- Camino tiquetera (0097): reserva sin cobrar, con su propio saldo,\n  -- jugando en el mismo cupo que la clase suelta -- no crea capacidad\n  -- nueva, solo cambia cuándo se cobró la clase.\n  ------------------------------------------------------------------\n  if p_tipo = ''tiquetera'' then\n    select * into v_tiquetera from tiqueteras\n     where codigo = upper(trim(coalesce(p_codigo_tiquetera, '''')))\n       and activa\n       and vence_el >= v_fecha\n       and clases_usadas < clases_totales\n     for update;\n\n    if not found then\n      return jsonb_build_object(''ok'', false, ''error'', ''TIQUETERA_INVALIDA'',\n        ''mensaje'', ''Ese código de tiquetera no es válido, ya venció o ya no ''\n                || ''tiene clases disponibles. Escríbenos por WhatsApp si ''\n                || ''crees que es un error.'');\n    end if;\n\n    v_estado := ''confirmada'';\n  end if;\n\n  ------------------------------------------------------------------\n  -- Cupo compartido: el techo de la sala, siempre manda';
  v_a4 constant text := E'  if v_tope is not null then\n    select count(*) into v_tomadas\n      from reservas r\n     where r.clase_id = p_clase_id\n       and r.tipo = p_tipo::tipo_reserva\n       and r.estado not in (''rechazada'', ''expirada'');\n    if v_tomadas >= v_tope then';
  v_n4 constant text := E'  if v_tope is not null then\n    select count(*) into v_tomadas\n      from reservas r\n     where r.clase_id = p_clase_id\n       -- 0097: suelta y tiquetera comparten el mismo cupo: una\n       -- tiquetera vendida es, para este conteo, una silla de suelta\n       -- que ya se pagó antes.\n       and r.tipo = any(case when p_tipo in (''suelta'', ''tiquetera'')\n                              then array[''suelta'', ''tiquetera'']::tipo_reserva[]\n                              else array[p_tipo::tipo_reserva] end)\n       and r.estado not in (''rechazada'', ''expirada'');\n    if v_tomadas >= v_tope then';
  v_a5 constant text := E'      insert into reservas (codigo, clase_id, nombre, telefono, email,\n                            origen, tipo, estado, membresia_id)\n      values (v_codigo, p_clase_id, p_nombre, v_tel, p_email,\n              p_origen, p_tipo::tipo_reserva, v_estado, v_memb_id)\n      returning * into v_reserva;\n      exit;';
  v_n5 constant text := E'      insert into reservas (codigo, clase_id, nombre, telefono, email,\n                            origen, tipo, estado, membresia_id, tiquetera_id)\n      values (v_codigo, p_clase_id, p_nombre, v_tel, p_email,\n              p_origen, p_tipo::tipo_reserva, v_estado, v_memb_id, v_tiquetera.id)\n      returning * into v_reserva;\n      exit;';
  v_a6 constant text := E'    end;\n  end loop;\n\n  return jsonb_build_object(\n    ''ok'', true,';
  v_n6 constant text := E'    end;\n  end loop;\n\n  -- 0097: el saldo se descuenta cuando la reserva ya quedó insertada\n  -- -- si algo de arriba fallara, no queremos una tiquetera gastada sin\n  -- una reserva real detrás.\n  if p_tipo = ''tiquetera'' then\n    update tiqueteras set clases_usadas = clases_usadas + 1\n     where id = v_tiquetera.id;\n  end if;\n\n  return jsonb_build_object(\n    ''ok'', true,';
  v_a7 constant text := E'    ''precio_cop'',  v_clase.precio_cop,\n    ''cupos_restantes'', greatest(v_clase.cupo_total - v_clase.cupo_tomado - 1, 0));\nend;';
  v_n7 constant text := E'    ''precio_cop'',  v_clase.precio_cop,\n    ''cupos_restantes'', greatest(v_clase.cupo_total - v_clase.cupo_tomado - 1, 0),\n    ''tiquetera_saldo'', case when p_tipo = ''tiquetera''\n      then v_tiquetera.clases_totales - v_tiquetera.clases_usadas - 1\n      else null end);\nend;';
begin
  select pg_get_functiondef(p.oid) into v_src
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'tomar_cupo' and p.prokind = 'f';
  if v_src is null then raise exception '0097: no existe public.tomar_cupo'; end if;

  if position('0097:' in v_src) > 0 then
    raise notice '0097: tomar_cupo ya aplicado, no se toca';
  else
    if position(v_a1 in v_src) = 0 then raise exception '0097: falta anchor 1'; end if;
    v_src := replace(v_src, v_a1, v_n1);
    if position(v_a2 in v_src) = 0 then raise exception '0097: falta anchor 2'; end if;
    v_src := replace(v_src, v_a2, v_n2);
    if position(v_a3 in v_src) = 0 then raise exception '0097: falta anchor 3'; end if;
    v_src := replace(v_src, v_a3, v_n3);
    if position(v_a4 in v_src) = 0 then raise exception '0097: falta anchor 4'; end if;
    v_src := replace(v_src, v_a4, v_n4);
    if position(v_a5 in v_src) = 0 then raise exception '0097: falta anchor 5'; end if;
    v_src := replace(v_src, v_a5, v_n5);
    if position(v_a6 in v_src) = 0 then raise exception '0097: falta anchor 6'; end if;
    v_src := replace(v_src, v_a6, v_n6);
    if position(v_a7 in v_src) = 0 then raise exception '0097: falta anchor 7'; end if;
    v_src := replace(v_src, v_a7, v_n7);
    execute v_src;
  end if;
end
$mig$;

-- ── 6. admin_marcar_no_vino distingue tiquetera de miembro ───────────
do $mig$
declare
  v_src text;
  v_a constant text := E'  if v_res.tipo <> ''suelta'' then\n    return jsonb_build_object(''ok'', false, ''error'', ''ES_MIEMBRO'',\n      ''mensaje'', ''Quien viene por mensualidad no pierde una clase pagada.'');\n  end if;';
  v_n constant text := E'  -- 0097: la tiquetera no le regala nada al no show -- el cupo ya se\n  -- gastó al reservar, distinto de miembro (que nunca pagó por esa\n  -- silla puntual).\n  if v_res.tipo = ''tiquetera'' then\n    return jsonb_build_object(''ok'', false, ''error'', ''ES_TIQUETERA'',\n      ''mensaje'', ''La tiquetera ya descontó esa clase al reservar. No hay nada que anotar aquí.'');\n  end if;\n  if v_res.tipo <> ''suelta'' then\n    return jsonb_build_object(''ok'', false, ''error'', ''ES_MIEMBRO'',\n      ''mensaje'', ''Quien viene por mensualidad no pierde una clase pagada.'');\n  end if;';
begin
  select pg_get_functiondef(p.oid) into v_src
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'admin_marcar_no_vino' and p.prokind = 'f';
  if v_src is null then raise exception '0097: no existe public.admin_marcar_no_vino'; end if;

  if position('0097:' in v_src) > 0 then
    raise notice '0097: admin_marcar_no_vino ya aplicado, no se toca';
  else
    if position(v_a in v_src) = 0 then raise exception '0097: falta anchor de admin_marcar_no_vino'; end if;
    execute replace(v_src, v_a, v_n);
  end if;
end
$mig$;
